version: '3.8'

services:
  backend:
    build: server/
    container_name: krutorus-backend
    ports:
      - "8080:8080"
    env_file:
      - server/.env 
    volumes:
      - ./config:/app/config:ro  
    restart: unless-stopped

secrets:
  protorus_env:
    file: server/.env 